name: Release and Publish
permissions:
  contents: write
  id-token: write
  packages: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  install:
    uses: ./.github/workflows/install.job.yml

  lint:
    needs: install
    uses: ./.github/workflows/lint.job.yml

  typecheck:
    needs: install
    uses: ./.github/workflows/typecheck.job.yml

  tests:
    needs: install
    uses: ./.github/workflows/unit-tests.job.yml

  build:
    needs:
      - install
      - lint
      - typecheck
      - tests
    uses: ./.github/workflows/build.job.yml

  publish:
    needs:
      - install
      - build
    uses: ./.github/workflows/publish.job.yml
    permissions:
      id-token: write
